// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASyJL7uHqAAgq9LP45OFYsYT6kHvFhB_o',
    appId: '1:346793414426:web:0e626449cec8ffe5c966a3',
    messagingSenderId: '346793414426',
    projectId: 'myteach-35a14',
    authDomain: 'myteach-35a14.firebaseapp.com',
    storageBucket: 'myteach-35a14.appspot.com',
    measurementId: 'G-GW7H9GX0DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjl3BoodedDaHDCnTP9Lz7WQGP2Q7r9rw',
    appId: '1:346793414426:android:f388e1663df8c207c966a3',
    messagingSenderId: '346793414426',
    projectId: 'myteach-35a14',
    storageBucket: 'myteach-35a14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwTnZzPEgYjqNN0rphB36G0Wt4rjBdjLw',
    appId: '1:346793414426:ios:697a403d5291b4dfc966a3',
    messagingSenderId: '346793414426',
    projectId: 'myteach-35a14',
    storageBucket: 'myteach-35a14.appspot.com',
    iosClientId: '346793414426-9n86dk2rmvcbufr0oa7pvlhehohvq8es.apps.googleusercontent.com',
    iosBundleId: 'com.myteach.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwTnZzPEgYjqNN0rphB36G0Wt4rjBdjLw',
    appId: '1:346793414426:ios:ee0c08e8e07abbb6c966a3',
    messagingSenderId: '346793414426',
    projectId: 'myteach-35a14',
    storageBucket: 'myteach-35a14.appspot.com',
    iosClientId: '346793414426-uu2a9rpj99hbhijrmdbnritqdh3cqrg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
